language: ruby
rvm:
  - 2.5.7
  - 2.6.5
env:
  - AR="~> 5.1.7" SQL="~>1.3.6" NOKOGIRI_USE_SYSTEM_LIBRARIES=1
  - AR="~> 5.2.4" SQL="~>1.3.6" NOKOGIRI_USE_SYSTEM_LIBRARIES=1
  - AR="~> 6.0.0" SQL="~>1.4" NOKOGIRI_USE_SYSTEM_LIBRARIES=1
script: bundle exec rake specs:travis
